"""update alerts for detection

Revision ID: 776d395833e1
Revises: 50ac1da3b9e0
Create Date: 2026-05-31 14:32:58.166287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776d395833e1'
down_revision: Union[str, Sequence[str], None] = '50ac1da3b9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('detection_rule_id', sa.Integer(), nullable=False))
    op.add_column('alerts', sa.Column('risk_score', sa.Integer(), nullable=False))
    op.add_column('alerts', sa.Column('source_ip', sa.Text(), nullable=True))
    op.add_column('alerts', sa.Column('username', sa.Text(), nullable=True))
    op.add_column('alerts', sa.Column('event_count', sa.Integer(), nullable=False))
    op.add_column('alerts', sa.Column('first_seen_at', sa.DateTime(), nullable=False))
    op.add_column('alerts', sa.Column('last_seen_at', sa.DateTime(), nullable=False))
    op.alter_column('alerts', 'severity',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('alerts', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_foreign_key(None, 'alerts', 'detection_rules', ['detection_rule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.alter_column('alerts', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('alerts', 'severity',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('alerts', 'last_seen_at')
    op.drop_column('alerts', 'first_seen_at')
    op.drop_column('alerts', 'event_count')
    op.drop_column('alerts', 'username')
    op.drop_column('alerts', 'source_ip')
    op.drop_column('alerts', 'risk_score')
    op.drop_column('alerts', 'detection_rule_id')
    # ### end Alembic commands ###
