"""add destination port to security events

Revision ID: 78268944ba19
Revises: 776d395833e1
Create Date: 2026-05-31 15:31:23.832143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78268944ba19'
down_revision: Union[str, Sequence[str], None] = '776d395833e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_events', sa.Column('destination_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_events', 'destination_port')
    # ### end Alembic commands ###
