"""extend incidents for investigation workflow

Revision ID: 99c72af5643b
Revises: 78268944ba19
Create Date: 2026-06-01 10:27:09.067226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c72af5643b'
down_revision: Union[str, Sequence[str], None] = '78268944ba19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('incidents', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('incidents', sa.Column('created_from_alert_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incidents', 'alerts', ['created_from_alert_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'created_from_alert_id')
    op.drop_column('incidents', 'resolved_at')
    op.drop_column('incidents', 'updated_at')
    # ### end Alembic commands ###
